### ISSUE TITLE
mgadm should handle API errors gracefully

### ISSUE THREAD

**Issue by rcgoodfellow** [oxidecomputer/maghemite#362]
There are several places like this in the `mgadm` code where we unwrap API calls like this.

https://github.com/oxidecomputer/maghemite/blob/252491373e369ff86eafe3703a5b536bf7cf3a40/mgadm/src/bgp.rs#L584

This results in a crash and corefile when the API returns an error, even for something like a 400 error. While `mgadm` is just a local debugging tool, this is not ideal as it leaves core files around which show up in rack health checks.

**Comment by elaine-oxide** [comment]
More detailed example:

On madrid with R13 (v13/rc2) (incomplete installation, but switch zone running), I tried the following, even though I do not have BGP configured (nor is ASN `65547` specified anywhere).

```
root@oxz_switch1:~# mgadm bgp config router list
[]

root@oxz_switch1:~# mgadm bgp status neighbors 65547
thread 'main' panicked at mgadm/src/bgp.rs:648:45:
called `Result::unwrap()` on an `Err` value: Error Response: status: 404 Not Found; headers: {"content-type": "application/json", "x-request-id": "6b8787b1-ed09-43e5-aab1-f2bb5414eaa2", "content-length": "84", "date": "Wed, 31 Dec 1986 00:51:59 GMT"}; value: Error { error_code: None, message: "Not Found", request_id: "6b8787b1-ed09-43e5-aab1-f2bb5414eaa2" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Abort (core dumped)

root@oxz_switch1:~# mgadm bgp status imported 65547
thread 'main' panicked at mgadm/src/bgp.rs:705:10:
called `Result::unwrap()` on an `Err` value: Error Response: status: 404 Not Found; headers: {"content-type": "application/json", "x-request-id": "4110ec54-38a7-45b1-bbfa-b146885c2019", "content-length": "84", "date": "Wed, 31 Dec 1986 00:52:59 GMT"}; value: Error { error_code: None, message: "Not Found", request_id: "4110ec54-38a7-45b1-bbfa-b146885c2019" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Abort (core dumped)
```

```
root@oxz_switch1:~# RUST_BACKTRACE=1 mgadm bgp status neighbors 65547
thread 'main' panicked at mgadm/src/bgp.rs:648:45:
called `Result::unwrap()` on an `Err` value: Error Response: status: 404 Not Found; headers: {"content-type": "application/json", "x-request-id": "fe1974be-a704-4a96-9e16-ecc138dfd7f4", "content-length": "84", "date": "Wed, 31 Dec 1986 01:47:55 GMT"}; value: Error { error_code: None, message: "Not Found", request_id: "fe1974be-a704-4a96-9e16-ecc138dfd7f4" }
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: mgadm::bgp::commands::{{closure}}
   4: mgadm::main::{{closure}}
   5: tokio::runtime::park::CachedParkThread::block_on
   6: tokio::runtime::context::runtime::enter_runtime
   7: mgadm::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Abort (core dumped)
```

Expected behavior is no core dump.
